name: Start and test the application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Install npm
      run: npm install
    - name: Run tests
      run: npm test
    - name: Deploy on Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.RENDER_TOKEN }}
        wait-for-success: true
